theme: jekyll-theme-minimal
title: Brendan Octaviano
description: Showcasing data analysis projects I have completed
github:
  is_project_page: false

<a href="https://www.linkedin.com/in/brendanoct/"> My LinkedIn </a>
<a href="mailto:brendanoct04@gmail.com">E-mail me!</a>
