theme: jekyll-theme-minimal
title: Brendan Octaviano
description: Showcasing data analysis projects I have completed! Please click on each project's heading to view my analysis and code
github:
  is_project_page: false
